# This section has all data saving options present.
# Current available data sources are: MySQL & Flat
DataOptions:
  Source: FLAT
  # Leave this to true unless you are 100% sure that
  # the server will never crash / be force stopped.
  Auto-Save: true

# This section has all database options present.
# NOTE: This configuration will only be of importance if
#       "DataOptions -> Source" is set to MySQL.
Database:
  Authorization:
    Username: "root"
    Password: ""
  URL:
    Address: "localhost"
    Port: 3306
  Information:
    Database: "dustypvp"
    Users-Table: "users"

# This section has all options for the internal chat system.
# Leave to false if another plugin is handling the chat format etc.
Internal-Chat:
  Enabled: false
  Format: "&d{player}&7: &f{message}"
  ToolTip: [
    "&f* &5Kills: &d{kills}",
    "&f* &5Deaths: &d{deaths}",
    "&f* &5KDR: &d{kdr}"
  ]

# This section has all options for the internal scoreboard.
# Leave to false if another plugin is handling the scoreboard.
Internal-Scoreboard:
  Enabled: false
  Custom-Score:
    Enabled: true
    Score: 0
  Title: "&f&l<*> &5&lDustyPvP &f&l<*>"
  Lines: [
    "&f&m--------------------",
    "&d&lYOU",
    "&f &f* &5Name: &f%player_name%",
    "&f &f* &5Ping: &f%player_ping%",
    "&r",
    "&d&lSTATS",
    "&f &f* &5Kills: &f%dustypvp_kills%",
    "&f &f* &5Deaths: &f%dustypvp_deaths%",
    "&f&m--------------------"
  ]